---

- hosts: webservers

  become: yes

  tasks:
  - debug: var=ansible_default_ipv4.address
  - name: Installs nginx web server on devA devB and devC

    apt:

      name: nginx

      state: present

      update_cache: true
    notify:

    - start nginx

  - name: Installs php on devA devB and devC

    apt:

      name: php

      state: present

      update_cache: true



  - name: Installs php-fpm on devA devB and devC

    apt:

      name: php-fpm

      state: present

      update_cache: true

    notify:

    - start php7.4-fpm

  - name: keeping php7.4-fpm cgi.fix_pathinfo=0 to run the php files on nginx
    lineinfile: dest=/etc/php/7.4/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
    notify:
    - restart php7.4-fpm
    - restart nginx

  - name: Removes "nginx.conf" site at etc/nginx/
    file:
       path: "/etc/nginx/nginx.conf"
       state: absent
  
  - name: Sets nginx.conf file at etc/nginx/
    template:
       src: "./Nginx.conf.j2"
       dest: "/etc/nginx/nginx.conf"
    notify:
    - restart php7.4-fpm
    - restart nginx



  - name: Removes "default" site at etc/nginx/sites-enabled
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent
    notify: 
    - restart nginx

  - name: Sets Nginx conf file at etc/nginx/sites-available
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: links default etc/nginx/sites-available to the etc/nginx/sites-enable
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link
    notify: 
    - restart nginx
   

  - name: "UFW - Allow HTTP on port 80 to connect connections for the nginx"
    ufw:
       rule: allow
       port: '80'
       proto: any


  - name: Sets Up index.PHP Page at root var/www/html
    template:
      src: "./index.php"
      dest: "/var/www/html/index.php"
    notify:
    - restart nginx
    - start nginx
    - restart php7.4-fpm
    - start php7.4-fpm 


  handlers:

  - name: start php7.4-fpm
    service:

      name: php7.4-fpm

      state: started



  - name: start nginx
    service:

      name: nginx

      state: started


  - name: restart php7.4-fpm
    service:

      name: php7.4-fpm

      state: restarted
  - name: restart nginx

    service:

      name: nginx

      state: restarted
- hosts: haproxy
  become: yes

  tasks:
  - debug: var=ansible_default_ipv4.address


  - name: Installs haproxy load balancer on devhaproxy load balancer
    apt:
      name: haproxy
      state: present
      update_cache: true

  - name: locates haproxy configuration with jinja2 template file at /etc/haproxy/haproxy.cfg
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: 0640
      owner: root
      group: root
    notify:
    - restart haproxy
  - name: Sets default starting flag to 1 to enable haproxy
    lineinfile:
      dest: /etc/default/haproxy
      regexp: "^ENABLED"
      line: "ENABLED=1"
    notify:
    - restart haproxy


  handlers:
  
  - name: restart haproxy
    service:
        name: haproxy
        state: restarted

   
...
